### ISSUE TITLE
TMFS: markdown in comments?

### ISSUE THREAD

**Issue by boblsturm** [tobyspark/folk-rnn-webapp#110]
Trying to make a link on my comment here: https://themachinefolksession.org/tune-of-the-month/1 

Is there a reason to not allow links here?

**Comment by tobyspark** [comment]
I might have been trying to keep things simple or stop spam links... but, yeah, no solid reason. I will make it render these as markdown.

**Comment by tobyspark** [comment]
Instead of markdown, which requires you to format links in a specific way, I've filtered the plain text through `urlize`, which just turns URLs into clickable links. Should be what most people expect, and will keep the formatting of comments minimal.

So, description fields when you contribute a tune, recording, tune of the month etc. are markdown, but everything else should just urlize.
